// This file is generated by Dreamflow. Do not edit.
import 'dart:convert';
import 'dart:async';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'dart:developer' as dev;

import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart' show MaterialApp;
import 'wrap_preview.dart';

import '78c97c4a/17c68e3fec6f4b62.dart' as p0;
import '1c80ed25/b6abc4417ba94d2f.dart' as p1;
import '0830f3e5/3105872ea62d4974.dart' as p2;
import '63060514/32b4a46492fe4333.dart' as p3;
import '5650373f/fed88388c92041fe.dart' as p4;
import 'ebb40a32/59b2b39ecf4349d3.dart' as p5;
import '90d062f4/d274afa257a24045.dart' as p6;
import '5190dcb4/ebd6b9fb16374694.dart' as p7;
import '2cc1e674/8477cb3a469647c7.dart' as p8;
import '82d424b7/56799d3b1c814df6.dart' as p9;
import '182785e4/aec27c5a8bce4c3e.dart' as p10;
import 'a1d2354d/a9e60ef4867b46b1.dart' as p11;
import '2af2f3b2/cdfcd3e983334eed.dart' as p12;
import '9c9e6098/7e842a1e76744170.dart' as p13;
import 'e7bf00d4/471dcb2567db44bb.dart' as p14;
import '7d461fb4/c122acf778da4360.dart' as p15;
import '19483c30/abd154df6d024504.dart' as p16;
import '30a1cdf4/e586d4d2209443a7.dart' as p17;
import '1d96a8b1/ce0550303f714c9e.dart' as p18;
import '1721fdc5/bfd7e268c67e4348.dart' as p19;
import 'ad721fb4/af7e8caa92ad4bc7.dart' as p20;
import '9ae9081e/ae7ce130fe7047e3.dart' as p21;
import '8c590a65/ca0b75347e794904.dart' as p22;
import '53975ca5/e8ef8f3fda4147c3.dart' as p23;
import 'f471c434/2109505f320642dd.dart' as p24;
import '4d5445d7/676b839f7b5844c5.dart' as p25;
import '0e68f4e5/25a5efd7075046fc.dart' as p26;
import 'b454fbb1/05d9830d1be548ff.dart' as p27;
import '1f6ec265/732d85af00b241f5.dart' as p28;
import '732647bd/0975996f734f460e.dart' as p29;
import '552c4a32/556f9a887e124c7f.dart' as p30;
import 'd571fe41/727ee444c09e4b75.dart' as p31;
import '64ef28e5/8aacb5304019443e.dart' as p32;
import 'de69580d/2ef58dc54f2b428f.dart' as p33;
import '5eca9cb4/739b46ff6dfd4769.dart' as p34;
import '8d418ef4/8d4e2654ce1348a4.dart' as p35;
import 'bb6311bb/78ef6cb59d7e4fbe.dart' as p36;
import '374ce7d4/0127a8e41c9f400e.dart' as p37;
import 'f7bca6b4/9671e94974bc4b19.dart' as p38;

void main() async {
  final controller = StreamController<String>(sync: true);
  dev.registerExtension('ext.hologram.showPreviewVariant', (_, params) {
    final previewId = params['previewId'];
    if (previewId case final String previewId) {
      controller.add(previewId);
    }
    return Future.value(dev.ServiceExtensionResponse.result(''));
  });

  await initializePreviewApp();

  runApp(_PreviewRunner(controller.stream));
}

class _PreviewRunner extends StatelessWidget {
  const _PreviewRunner(this.stream);

  final Stream<String> stream;

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: stream,
      builder: (context, snapshot) {
        final preview = switch (snapshot.data) {
          '17c68e3fec6f4b62' => p0.preview_UkCol,
          'b6abc4417ba94d2f' => p1.preview_UkBadge,
          '3105872ea62d4974' => p2.preview_UkDivider,
          '32b4a46492fe4333' => p3.preview_UkSticky,
          'fed88388c92041fe' => p4.preview_UkCheckbox,
          '59b2b39ecf4349d3' => p5.preview_UkSection,
          'd274afa257a24045' => p6.preview_UkButton,
          'ebd6b9fb16374694' => p7.preview_UkNavbar,
          '8477cb3a469647c7' => p8.preview_UkAlert,
          '56799d3b1c814df6' => p9.preview_showUkOffcanvas,
          'aec27c5a8bce4c3e' => p10.preview_UkTextField,
          'a9e60ef4867b46b1' => p11.preview_UkSlider,
          'cdfcd3e983334eed' => p12.preview_UkGrid,
          '7e842a1e76744170' => p13.preview_showUkModalSheet,
          '471dcb2567db44bb' => p14.preview_UkBreadcrumb,
          'c122acf778da4360' => p15.preview_UkAccordion,
          'abd154df6d024504' => p16.preview_HomePage,
          'e586d4d2209443a7' => p17.preview_UkScrollspy,
          'ce0550303f714c9e' => p18.preview_UkTextArea,
          'bfd7e268c67e4348' => p19.preview_UkList,
          'af7e8caa92ad4bc7' => p20.preview_UkCarousel,
          'ae7ce130fe7047e3' => p21.preview_UkSwitch,
          'ca0b75347e794904' => p22.preview_UkSpinner,
          'e8ef8f3fda4147c3' => p23.preview_UkProgress,
          '2109505f320642dd' => p24.preview_UkTabs,
          '676b839f7b5844c5' => p25.preview_showUkLightbox,
          '25a5efd7075046fc' => p26.preview_UkIcon,
          '05d9830d1be548ff' => p27.preview_UkListTile,
          '732d85af00b241f5' => p28.preview_UkHeading,
          '0975996f734f460e' => p29.preview_UkRadio,
          '556f9a887e124c7f' => p30.preview_UkContainer,
          '727ee444c09e4b75' => p31.preview_UkSubnav,
          '8aacb5304019443e' => p32.preview_UkTable,
          '2ef58dc54f2b428f' => p33.preview_UkSelect,
          '739b46ff6dfd4769' => p34.preview_UkCard,
          '8d4e2654ce1348a4' => p35.preview_UkTooltip,
          '78ef6cb59d7e4fbe' => p36.preview_UkModalSheet,
          '0127a8e41c9f400e' => p37.preview_UkDropdown,
          '9671e94974bc4b19' => p38.preview_UkPagination,
          final String previewId => () => Center(child: Text('Error: Unknown preview identifier: $previewId')),
          null => () => const SizedBox.shrink(),
        };
        return Directionality(
          textDirection: TextDirection.ltr,
          // Ensuring there is hijacking navigator as the top-most navigator.
          child: _Navigator(
            snapshot.data, 
            // Ensuring that in between the wrapPreview and the preview there is a hijacking navigator.
            child: wrapPreview(() => _Navigator(snapshot.data, child: preview())),
          ),
        );
      },
    );
  }
}

class _Navigator extends Navigator {
  _Navigator(this.previewId, {required Widget child})
    : super(pages: [_Page(child: child)]);

  final String? previewId;

  @override
  NavigatorState createState() => _NavigatorState();
}

class _NavigatorState extends NavigatorState {
  @override
  _Navigator get widget => super.widget as _Navigator;

  @override
  Future<T?> push<T extends Object?>(Route<T> route) {
    if (widget.previewId case final String previewId) {
      final buffer = toArrayBuffer({
        'previewId': previewId,
        'type': 'Navigation.push',
      });
      final transfer = ([buffer] as List<JSAny?>).toJS;
      postMessage(buffer, '*'.toJS, transfer);
    }

    return Future.value(null);
  }

  @override
  void pop<T extends Object?>([T? result]) {
    if (widget.previewId case final String previewId) {
      final buffer = toArrayBuffer({
        'previewId': previewId,
        'type': 'Navigation.pop',
      });
      final transfer = ([buffer] as List<JSAny?>).toJS;
      postMessage(buffer, '*'.toJS, transfer);
    }
  }
}

class _Page<T> extends Page<T> {
  const _Page({required this.child});

  final Widget child;

  @override
  Route<T> createRoute(BuildContext context) => _PageRoute<T>(page: this);
}

class _PageRoute<T> extends PageRoute<T> {
  _PageRoute({required _Page<T> page}) : super(settings: page);

  _Page<T> get _page => settings as _Page<T>;

  @override
  bool get maintainState => false;

  @override
  Duration get transitionDuration => Duration.zero;

  @override
  Color? get barrierColor => Color(0x00000000);

  @override
  String? get barrierLabel => null;

  @override
  Widget buildPage(BuildContext _, Animation<double> __, Animation<double> ___) {
    return _page.child;
  }
}

@JS(r'window.parent.postMessage')
external void postMessage(
  JSArrayBuffer message,
  JSString targetOrigin, [
  JSArray<JSAny?>? transfer,
]);

JSArrayBuffer toArrayBuffer(Object obj) {
  final encoder = JSTextEncoder();
  final bytes = encoder.encode(jsonEncode(obj));
  return _arrayBufferOf(bytes);
}

JSArrayBuffer _arrayBufferOf(JSUint8Array uint8) =>
    (uint8 as JSObject)['buffer'] as JSArrayBuffer;

@JS('TextDecoder')
extension type JSTextDecoder._(JSObject _) implements JSObject {
  external factory JSTextDecoder([String label]);
  external String decode([JSArrayBuffer input]);
}

@JS('TextEncoder')
extension type JSTextEncoder._(JSObject _) implements JSObject {
  external factory JSTextEncoder();
  external JSUint8Array encode([String input]);
}
